# Generated by Django 6.0.3 on 2026-03-19 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("current_section", models.CharField(blank=True, max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("listening_start", models.DateTimeField(blank=True, null=True)),
                ("reading_start", models.DateTimeField(blank=True, null=True)),
                ("writing_start", models.DateTimeField(blank=True, null=True)),
                ("speaking_start", models.DateTimeField(blank=True, null=True)),
                ("listening_end", models.DateTimeField(blank=True, null=True)),
                ("reading_end", models.DateTimeField(blank=True, null=True)),
                ("writing_end", models.DateTimeField(blank=True, null=True)),
                ("speaking_end", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.examset",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField(blank=True)),
                ("duration_minutes", models.IntegerField()),
                ("order", models.IntegerField(default=0)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="listening/"),
                ),
                (
                    "exam_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="exams.examset",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReadingPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="exams.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("fill_blank", "Fill in the Blank"),
                            ("true_false_ng", "True/False/Not Given"),
                            ("matching", "Matching Headings"),
                            ("sentence_completion", "Sentence Completion"),
                            ("map_labelling", "Map Labelling"),
                            ("essay_task1", "Writing Task 1"),
                            ("essay_task2", "Writing Task 2"),
                            ("speaking", "Speaking"),
                        ],
                        max_length=30,
                    ),
                ),
                ("question_text", models.TextField()),
                ("question_number", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="writing/"),
                ),
                ("option_a", models.CharField(blank=True, max_length=500)),
                ("option_b", models.CharField(blank=True, max_length=500)),
                ("option_c", models.CharField(blank=True, max_length=500)),
                ("option_d", models.CharField(blank=True, max_length=500)),
                ("correct_answer", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("speaking_part", models.IntegerField(blank=True, null=True)),
                (
                    "passage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.readingpassage",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.section",
                    ),
                ),
            ],
            options={
                "ordering": ["question_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="speaking/"),
                ),
                ("is_correct", models.BooleanField(null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="exams.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
