# Generated by Django 6.0.3 on 2026-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("fill_blank", "Fill in the Blank"),
                    ("true_false_ng", "True/False/Not Given"),
                    ("yes_no_ng", "Yes/No/Not Given"),
                    ("matching", "Matching Headings"),
                    ("sentence_completion", "Sentence Completion"),
                    ("map_labelling", "Map Labelling"),
                    ("essay_task1", "Writing Task 1"),
                    ("essay_task2", "Writing Task 2"),
                    ("speaking", "Speaking"),
                ],
                max_length=30,
            ),
        ),
    ]
