# Generated by Django 6.0.3 on 2026-05-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_question_question_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("youtube_url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
